---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-2000-digits

spec:
  template:
    spec:
      containers:
      - name: pi-2000-digits
        image: perl:slim
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
...
