---
- name: Define Docker cgroup as "systemd"
  copy:
    src: daemon.json
    dest: /etc/docker/
  tags: master

- name: Restart Docker
  systemd:
    name: docker.service
    state: restarted
    daemon_reload: yes
  tags: master

- name: Initialize the Kubernetes cluster
  shell: "kubeadm init --apiserver-advertise-address={{ master_ip }} --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt"
  args:
    chdir: /root
    creates: cluster_initialized.txt
  tags: master

- name: Save Kubernetes join command
  shell: "kubeadm token create --print-join-command > join.txt"
  args:
    chdir: /root
    creates: join.txt
  tags: master

- name: Copy join.txt file from target to localhost
  fetch:
    src: /root/join.txt
    dest: /tmp/
    flat: yes
  tags: master

- name: Create '.kube' directory
  file:
    path: /root/.kube
    state: directory
    mode: 0755
  tags: master

- name: Copy configuration file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  tags: master

- name: Install Flannel as Pod Network, so Pods can talk to each other
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  args:
    chdir: /root/
  tags: master
...
