---
- name: Initialize the Kubernetes cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: /home/vagrant
    creates: cluster_initialized.txt
  tags: master

- name: Create '.kube' directory
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: 0755
  tags: master

- name: Copy configuration file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
  tags: master

- name: Install Flannel as Pod Network, so Pods can talk to each other
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: /home/vagrant/
    creates: pod_network_setup.txt
  tags: master
...
